version: 2
jobs:
  test:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run: xvfb-run -a npm run test:ci
      - run: xvfb-run -a npm run e2e --config=protractor-ci.conf.js
  build_and_deploy:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: sudo npm install -g @angular/cli
      - run: sudo npm install -g angular-cli-ghpages
      - run: npm install

      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Generate Build
          command: xvfb-run -a npm run buildForGhPages
      - run:
          name: Publish to Github Pages
          command: xvfb-run -a sudo npx ngh --repo=https://$GH_TOKEN@github.com/LorcanChinnock/AngularCellAutomata.git --name="Lorcan Chinnock" --email=ljchinnock@gmail.com
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
